"""Create Projects, Products, Categories, and Images tables with relationships

Revision ID: 305b8296c136
Revises: c4b9c8f350c3
Create Date: 2024-06-27 11:15:17.929208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305b8296c136'
down_revision: Union[str, None] = 'c4b9c8f350c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=True),
    sa.Column('installer_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type_of_facility', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('realtime_electricity_generation', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('number_of_shares', sa.Integer(), nullable=True),
    sa.Column('cost_nok', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('money_required', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('money_spent', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('money_left', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('electricity_generation_prediction', sa.String(), nullable=True),
    sa.Column('manufacturer_status', sa.String(length=50), nullable=True),
    sa.Column('installer_status', sa.String(length=50), nullable=True),
    sa.Column('funded_status', sa.String(length=50), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['installer_id'], ['installers.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['share_id'], ['shares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
