"""Create SharesTable with relationships

Revision ID: 412292e77266
Revises: 305b8296c136
Create Date: 2024-06-27 11:20:41.599526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412292e77266'
down_revision: Union[str, None] = '305b8296c136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'shares', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shares', type_='foreignkey')
    # ### end Alembic commands ###
