"""Update Manufacturer and Installer tables

Revision ID: 846f98d65379
Revises: 412292e77266
Create Date: 2024-06-27 11:41:57.958921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846f98d65379'
down_revision: Union[str, None] = '412292e77266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_manufacturer_association',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], )
    )
    op.add_column('installers', sa.Column('comp_name', sa.String(length=255), nullable=True))
    op.add_column('installers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('installers', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('installers', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('installers', sa.Column('company_reg_number', sa.String(length=255), nullable=True))
    op.add_column('installers', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('installers', sa.Column('register_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'installers', 'accounts', ['account_id'], ['id'])
    op.drop_column('installers', 'experience_years')
    op.drop_column('installers', 'service_area')
    op.add_column('manufacturers', sa.Column('comp_name', sa.String(length=255), nullable=True))
    op.add_column('manufacturers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('manufacturers', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('manufacturers', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('manufacturers', sa.Column('comp_register_number', sa.String(length=255), nullable=True))
    op.add_column('manufacturers', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('manufacturers', sa.Column('register_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'manufacturers', 'accounts', ['account_id'], ['id'])
    op.drop_column('manufacturers', 'company_name')
    op.drop_column('manufacturers', 'industry')
    op.drop_constraint('projects_share_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_manufacturer_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'share_id')
    op.drop_column('projects', 'manufacturer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('manufacturer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('share_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_manufacturer_id_fkey', 'projects', 'manufacturers', ['manufacturer_id'], ['id'])
    op.create_foreign_key('projects_share_id_fkey', 'projects', 'shares', ['share_id'], ['id'])
    op.add_column('manufacturers', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('manufacturers', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'manufacturers', type_='foreignkey')
    op.drop_column('manufacturers', 'register_time')
    op.drop_column('manufacturers', 'company_size')
    op.drop_column('manufacturers', 'comp_register_number')
    op.drop_column('manufacturers', 'account_id')
    op.drop_column('manufacturers', 'zip_code')
    op.drop_column('manufacturers', 'address')
    op.drop_column('manufacturers', 'comp_name')
    op.add_column('installers', sa.Column('service_area', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('installers', sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'installers', type_='foreignkey')
    op.drop_column('installers', 'register_time')
    op.drop_column('installers', 'company_size')
    op.drop_column('installers', 'company_reg_number')
    op.drop_column('installers', 'account_id')
    op.drop_column('installers', 'zip_code')
    op.drop_column('installers', 'address')
    op.drop_column('installers', 'comp_name')
    op.drop_table('project_manufacturer_association')
    # ### end Alembic commands ###
