"""Add fields to Consumer, Manufacturer, Installer; Create Accounts and Shares tables

Revision ID: c4b9c8f350c3
Revises: 27d79b608ca5
Create Date: 2024-06-27 09:54:00.060817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b9c8f350c3'
down_revision: Union[str, None] = '27d79b608ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('consumers', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('installers', sa.Column('service_area', sa.String(), nullable=True))
    op.add_column('installers', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('manufacturers', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('manufacturers', sa.Column('industry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturers', 'industry')
    op.drop_column('manufacturers', 'company_name')
    op.drop_column('installers', 'experience_years')
    op.drop_column('installers', 'service_area')
    op.drop_column('consumers', 'phone_number')
    op.drop_column('consumers', 'address')
    # ### end Alembic commands ###
